name: Deploy Ediam Resources
#adding code to complete poc
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "container_app_imagename_poc" ]
#  pull_request:
#    branches-ignore:
#      - '*'

  # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:

 # Permissions setting indicates that an access token has to be used
permissions:
    id-token: write
    contents: read

    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     build_validate_create_container_app:
       # The type of runner that the job will run on
       #runs-on: windows-latest
       name: build and validate and create EDIAM Resource_Group on Dev
       #needs: [create-AZ-Connection]
       runs-on: ubuntu-latest
       steps:
         - name: Checkout self repo/branch
           uses: actions/checkout@v4
     
         - name: Login to Azure
           uses: azure/login@v1
           with:
                creds: ${{ secrets.AZURE_SPN_CREDENTIALS }}
         - name: Validating RG
           working-directory: ${{ github.workspace }}
           run: |
             chmod +x ./create_container_app.sh
             ./create_container_app.sh
             
              